### ISSUE TITLE
Table with MultiCells Trait Missing

### ISSUE THREAD

**Issue by systemsolutionweb** [fawno/FPDF#15]
http://www.fpdf.org/en/script/script3.php

_Description:_
The goal of this script is to show how to build a table from MultiCells.
As MultiCells go to the next line after being output, the base idea consists in saving the current position, printing the MultiCell and resetting the position to its right.
There is a difficulty, however, if the table is too long: page breaks. Before outputting a row, it is necessary to know whether it will cause a break or not. If it does overflow, a manual page break must be done first.
To do so, the height of the row must be known in advance; it is the maximum of the heights of the MultiCells it is made up of. To know the height of a MultiCell, the NbLines() method is used: it returns the number of lines a MultiCell will occupy.

**Comment by alphp** [comment]
Done, thanks @systemsolutionweb
