### ISSUE TITLE
PDF with signature

### ISSUE THREAD

**Issue by angeljqv** [fawno/FPDF#2]
See https://github.com/dealfonso/sapp

The signature guarantees the document's integrity and it allows the recipient to identify the signer of a document.

Any chances to have that functionality on FPDF?

**Comment by alphp** [comment]
SAPP is a very interesting project.
The signature implementation is also an interesting improvement.
However, being a complex implementation, I can't spend any efforts to create it.

If you need to sign a PDF, you can always use SAPP.
That said, if someone builds an implementation for FPDF, I'd be happy to add it.

**Comment by angeljqv** [comment]
Ok, thanks

**Comment by systemsolutionweb** [comment]
This functionality would be great in FPDF
