### ISSUE TITLE
FPDF Protection Script

### ISSUE THREAD

**Issue by angeljqv** [fawno/FPDF#3]
http://www.fpdf.org/en/script/script37.php

**FPDF Protection Script** prevent people from copying its content, print it or modify it.

```php
SetProtection([array permissions [, string user_pass [, string owner_pass]]])
```

**permissions:** the set of permissions. Empty by default (only viewing is allowed).
**user_pass:** user password. Empty by default.
**owner_pass:** owner password. If not specified, a random value is used.

**Comment by alphp** [comment]
I have added the trait inside Fawno\FPDF\Traits
It is available inside master:

```bash
composer require fawno/fpdf:dev-master
```

Thanks.

**Comment by angeljqv** [comment]
Thank you very much
